### ISSUE TITLE
highlight doesn't following code on game after scroll

### ISSUE THREAD

**Issue by DiogoVieiraFerreira** [Crepe-Party/ProgCraft#13]
![image](https://user-images.githubusercontent.com/47444284/103249402-4dc6be00-496f-11eb-90a5-2cb92f416f39.png)
when scroll on code section of game, the highlight doesn't follow the line

on the example, i've scroll before start

**Comment by BergmannFlorian** [comment]
Resolve by change the rectangle referenced to the scroll
