### ISSUE TITLE
[Game] on drag window on another screen, code start

### ISSUE THREAD

**Issue by DiogoVieiraFerreira** [Crepe-Party/ProgCraft#16]
when we select a program and drag game window on another screen, only the first time and randomly, after 10 test first time and 20 the second time, the code start automatically

<details>
  <summary>...</summary>
   @nicolas-maitre sorry it's a big feature, but we have to resolve it
   good luck
</details>

**Comment by nicolas-maitre** [comment]
Wtf

**Comment by DiogoVieiraFerreira** [comment]
yep quand je passe d'un écran à un autre j'ai le code qui se lance tout seul, comme si je cliquais sur start et je sais pas comment et pq 😅
